### ISSUE TITLE
Cannot install via Composer

### ISSUE THREAD

**Issue by bick** [leonstafford/wp2static-addon-github#3]
I downloaded and installed this plugin on my website, navigated to the plugin's directory, typed in `composer install` and it says `Composer could not find a composer.json file in /var/www/html/wp-content/plugins/wp2static-addon-github-master`. I also cannot activate the plugin in the backend because it says:

`Warning: require(/var/www/html/wp-content/plugins/wp2static-addon-github-master/includes/class-wp2static-addon-github.php): failed to open stream: No such file or directory in /var/www/html/wp-content/plugins/wp2static-addon-github-master/wp2static-addon-s3.php on line 62

Fatal error: require(): Failed opening required '/var/www/html/wp-content/plugins/wp2static-addon-github-master/includes/class-wp2static-addon-github.php' (include_path='.:/usr/share/php') in /var/www/html/wp-content/plugins/wp2static-addon-github-master/wp2static-addon-s3.php on line 62`

**Comment by ampliads** [comment]
Can not install this.
>downloaded the zip (as there is no composer file)
>uploaded through plugin interface.

Getting this error:
![2022-02-22_10-08-47](https://user-images.githubusercontent.com/71036669/155064105-55f23883-946e-4077-9997-6d2fe630896e.png)
